module.exports = {
	"BASE_URL":"https://api.themoviedb.org/3",
	"IMG_THUMB" : "http://image.tmdb.org/t/p/w500",
	"IMG_ORIGINAL" : "http://image.tmdb.org/t/p/original",
	"NOW_PLAYING" : "/movie/now_playing?",
	"UPCOMING" : "/movie/upcoming?",
	"POPULAR" : "/movie/popular?",
	"TOP_RATED" : "/movie/top_rated?",
	"LATEST_TV" : "/tv/on_the_air?",
	"POPULAR_TV" : "/tv/popular?",
	"TOP_RATED_TV" : "/tv/top_rated?",
	"SIMILAR" : "/similar?",
	"SEARCH" : "/search/multi?",
	"SEARCH_MOVIE" : "/search/movie?",
	"API_KEY" : "d6dadf6fd94626fca2e1aab19a6cf5e0",
	"GUEST_SESSION" : "/authentication/guest_session/new?",
}